### ISSUE TITLE
unable to generate tiles after optimization

### ISSUE THREAD

**Issue by moovida** [mikes222/mapsforge_flutter#10]
Hi, since I am using this in a bit different way than the usual, I am not able to understand from the code and example how to migrate after the new optimization changes.

I used to generate tile images with RendererJobs, which now got removed. I tried to fix it as:

```
Tile tile = new Tile(x, y, z, tileSize);
Job mapGeneratorJob = new Job(tile, false, userScaleFactor);
var resultTile = await _dataStoreRenderer.executeJob(mapGeneratorJob);
```

but this doesn't work anymore, throwing me an error:

```
I/flutter (  708): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
I/flutter (  708): #1      MapDataStoreRenderer.executeJob 
package:mapsforge_flutter/…/renderer/mapdatastorerenderer.dart:90
...
``` 

I am initializing everything as done in the example to open map and all the render and factory.
Is there anything else I have to take care of when running the render jobs "manually"?

Thanks for any hint.

**Comment by mikes222** [comment]
I have created a unit test for your usecase. While the test is not fully finished I am unable to reproduce your problem. The executeJob produces no exception. The problem may be solved already in my code. Please download the newest sources and retry your case. Eventually update the unittest to reflect your error. Keep me informed please.

**Comment by moovida** [comment]
Thanks a ton @mikes222 !
I rechecked everything and also cleaned up my assets and config files.

While I do not get the exception anymore, I am getting some issues on the rendering.

Sometimes it seems that not all the data are rendered inside a tile (the tile is the right one, but it doesn't contain all the data):

![image](https://user-images.githubusercontent.com/390250/87240980-c4521c80-c41e-11ea-8f13-9f8eb0e8f0d6.png)

In general I am not able to get all map tiles loaded (and some strange border lines appear):

![image](https://user-images.githubusercontent.com/390250/87241006-f794ab80-c41e-11ea-9ad5-dd789159d7a9.png)

The odd thing is that I am not getting exceptions of any kind. I wonder if I am missing an await somewhere, that wasn't necessary before these changes.

The only thing I see in the log are messages like:

```
unhandled element metadata; Picture key: packages/mapsforge_flutter/assets/patterns/farmland.svg
```

I think I saw the same for peak.svg before.

**Comment by mikes222** [comment]
I am still unable to reproduce your issue. Just a few thoughts: 
- try to clear the cache - purgeAll()
- Are always the same tiles affected?
- Try to create the tiles with a unittest and let it run multiple times, The example unittest is now working. Feel free to add more tests.
- double check your code with the unittest and see if there are any differences
- The parsing of your xml may fail somehow (guessed from your first image), please try the default renderer.xml or check if the parsing produces any exceptions.

The errormessage you mentioned comes from a missing or not-readable icon file. Check the assets-section in pubspec.yml and check if the file is really existing at the expected position. Create a unittest and see if the lib used is able to deal with the given file. 

Hope you can narrow down the problem.

**Comment by moovida** [comment]
Hi @mikes222 , I am playing with you testcase. While your works like a charm, I am not able to run this simple one:

Basically I want it to create 9 images to see how it behaves on multi image.

It freezes inside the mapDataStore.init() and I have no idea why. I guess I am doing something wrong, but I can't see it. Do you maybe? Thanks.


```
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:logging/logging.dart';
import 'package:mapsforge_flutter/core.dart';
import 'package:mapsforge_flutter/maps.dart';
import 'package:mapsforge_flutter/src/graphics/tilebitmap.dart';
import 'package:mapsforge_flutter/src/implementation/graphics/fluttertilebitmap.dart';
import 'package:mapsforge_flutter/src/layer/job/job.dart';
import 'package:mapsforge_flutter/src/model/tile.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('MapDataStoreRenderer', (WidgetTester tester) async {
    final DisplayModel displayModel = DisplayModel(
      maxZoomLevel: 15,
    );

    String prefix = ""; // "../";
    double tileSize = displayModel.tileSize;
    //15/43.7315/7.4177
    int z = 15;
    int x = MercatorProjectionImpl(tileSize, z).longitudeToTileX(7.4177);
    int y = MercatorProjectionImpl(tileSize, z).latitudeToTileY(43.7315);

    List<Tile> tilesToLoad = [
      Tile(x - 1, y - 1, z, tileSize),
      Tile(x - 1, y, z, tileSize),
      Tile(x - 1, y + 1, z, tileSize),
      Tile(x, y - 1, z, tileSize),
      Tile(x, y, z, tileSize),
      Tile(x, y + 1, z, tileSize),
      Tile(x + 1, y - 1, z, tileSize),
      Tile(x + 1, y, z, tileSize),
      Tile(x + 1, y + 1, z, tileSize),
    ];

    GraphicFactory graphicFactory = FlutterGraphicFactory();
    SymbolCache symbolCache = SymbolCache(displayModel);
    RenderThemeBuilder renderThemeBuilder =
        RenderThemeBuilder(graphicFactory, displayModel, symbolCache);
    final file = new File(prefix + 'test_resources/rendertheme.xml');
    String content = file.readAsStringSync();
    //String content = await rootBundle.loadString("assets/simplerender.xml");
    renderThemeBuilder.parseXml(content);
    RenderTheme renderTheme = renderThemeBuilder.build();
    MapFile mapDataStore = MapFile("./test_resources/monaco.map", 0, "en");
    await mapDataStore.init();

    for (var tile in tilesToLoad) {
      print("Reading tile ${tile.toString()}");
      MapDataStoreRenderer _dataStoreRenderer = MapDataStoreRenderer(
          mapDataStore, renderTheme, graphicFactory, false);
      Job mapGeneratorJob =
          new Job(tile, false, displayModel.getUserScaleFactor());

      TileBitmap resultTile =
          await _dataStoreRenderer.executeJob(mapGeneratorJob);
      assert(resultTile != null);
      var img = (resultTile as FlutterTileBitmap).bitmap;
      ByteData bytes = await img.toByteData(format: ImageByteFormat.png);
      var bytesList = bytes.buffer.asUint8List();
      File("./test_${tile.zoomLevel}/${tile.tileX}/${tile.tileY}.png")
          .writeAsBytesSync(bytesList);
    }
  });
}
```

**Comment by moovida** [comment]
Ok, I solved the above by rewriting the case like:

```
 testWidgets('MapDataStoreRenderer batch', (WidgetTester tester) async {
    _initLogging();
    final DisplayModel displayModel = DisplayModel(
      maxZoomLevel: 16,
    );

    String prefix = ""; // "../";
    double tileSize = displayModel.tileSize;
    //15/43.7315/7.4177
    int z = 15;
    int x = MercatorProjectionImpl(tileSize, z).longitudeToTileX(7.4177);
    int y = MercatorProjectionImpl(tileSize, z).latitudeToTileY(43.7315);

    List<Tile> tilesToLoad = [
      Tile(x - 1, y - 1, z, tileSize),
      Tile(x - 1, y, z, tileSize),
      Tile(x - 1, y + 1, z, tileSize),
      Tile(x, y - 1, z, tileSize),
      Tile(x, y, z, tileSize),
      Tile(x, y + 1, z, tileSize),
      Tile(x + 1, y - 1, z, tileSize),
      Tile(x + 1, y, z, tileSize),
      Tile(x + 1, y + 1, z, tileSize),
    ];

    GraphicFactory graphicFactory = FlutterGraphicFactory();
    SymbolCache symbolCache = SymbolCache(displayModel);
    RenderThemeBuilder renderThemeBuilder =
        RenderThemeBuilder(graphicFactory, displayModel, symbolCache);
    final file = new File(prefix + 'test_resources/rendertheme.xml');
    String content = file.readAsStringSync();
    //String content = await rootBundle.loadString("assets/simplerender.xml");
    renderThemeBuilder.parseXml(content);
    RenderTheme renderTheme = renderThemeBuilder.build();

    await tester.runAsync(() async {
      MapFile mapDataStore =
          MapFile(prefix + "test_resources/monaco.map", 0, "en");
      await mapDataStore.init();
      MapDataStoreRenderer _dataStoreRenderer = MapDataStoreRenderer(
          mapDataStore, renderTheme, graphicFactory, false);

      for (var tile in tilesToLoad) {
        print("Reading tile ${tile.toString()}");
        Job mapGeneratorJob =
            new Job(tile, false, displayModel.getUserScaleFactor());
            
        TileBitmap resultTile =
            await _dataStoreRenderer.executeJob(mapGeneratorJob);
        var img = (resultTile as FlutterTileBitmap).bitmap;

        ByteData bytes = await img.toByteData(format: ImageByteFormat.png);
        var bytesList = bytes.buffer.asUint8List();
        File("./test_${tile.zoomLevel}_${tile.tileX}_${tile.tileY}.png")
            .writeAsBytesSync(bytesList);
      }
      // return img;
    });
  });
```

and it works like a charm.


Then I fiddled around in the app I am inserting this and I am not able to get this working. I am reaching desperation.
The only thing I can think of, is the multithread behaviour the app has, which is happening in the testcase. 

Does this make sense? Is it possible that the threads are messing things up?

**Comment by moovida** [comment]
Last thing, I tried to move the 

```
MapDataStoreRenderer dataStoreRenderer = MapDataStoreRenderer(
        _mapDataStore, _renderTheme, _graphicFactory, true);
```

to be created new for every Job that is run. In that case things work correctly, even if the app crashes after a bit of panning and the performance is comparable to before, if not worse. So I assume that is not the way to go.

But it seems to tell me that the multithreading nature might be what is making rendering go wrong?

**Comment by mikes222** [comment]
Flutter do not have real multithreading. Everything is running in a single thread (with the exception of isolates), so there is no "real" concurrency. Even the testcase works more or less synchronously. 

- If it is memory related try running the performance analyzer of android studio and check what consumes memory. 
- You could also try setting the `direct` property in `MapDataStoreRenderer` to true and see if it works if the mapReader runs in the same thread (as opposed to an isolate). This is currently the only place in code where isolates are used. 
- Use the MemoryTileBitmapCache instead of FileTileBitmapCache as long as the problem persists. 
- Try to pan around in the example app and see if the same problem occurs. 
- Check if you call the `_dataStoreRenderer.executeJob` one after another or all at once and wait for all results concurrently?

The trimmed labels (if the label spans multiple tiles) are a known and documented problem. I had no time yet to fix it.

**Comment by moovida** [comment]
Hi @mikes222, thanks for the discussion.
Everything worked properly inside the flutter mapsforge project environment. But the problem of tiles generation from outside remained.

I finally got it working by control access to executeJob.
Basically it is enough for my kind of use to extend the renderer to add a controlled method **executeJobSync**:

```
class SmashMapDataStoreRenderer extends MapDataStoreRenderer {
  var lock = Lock();

  SmashMapDataStoreRenderer(MapDataStore mapDataStore, RenderTheme renderTheme,
      GraphicFactory graphicFactory, bool renderLabels)
      : super(mapDataStore, renderTheme, graphicFactory, renderLabels);

  Future<TileBitmap> executeJobSync(Job job) async {
    return await lock.synchronized(() async {
      return await executeJob(job);
    });
  }
}
```

**Comment by mikes222** [comment]
Glad to hear that. I will keep that in the queue to improve the datastorerenderer.

**Comment by moovida** [comment]
And btw, I forgot to mention the best thing. Performance improvement is notable. That is amazing, thank you!
