### ISSUE TITLE
Polyline capabilities

### ISSUE THREAD

**Issue by jamjr** [mikes222/mapsforge_flutter#111]
I have check the source code for the possibility to draw polylines as I need them for my project and I have found :  mapsforge_flutter/lib/src/paintelements/shape_paint_polyline.dart
But there is no documentation on how to  implement/use it.  Is not yet formally implemented? Is there a polyline datastore?. In the basic example you can find a marker example but nothing about polylines.  

Thank you anyway for your time implementing this nice library.

**Comment by mikes222** [comment]
Create a marker which draws as polyline like so:

``class PolygonMarker<T> extends BasicMarker<T> with BitmapMixin {``

and the drawMethod something like:

``  @override
  void renderBitmap(MapCanvas mapCanvas, MarkerContext markerContext) {``

...

      path.forEach((latLong) {
        Mappoint mappoint = markerContext.projection.latLonToPixel(latLong);
        double y = mappoint.y - markerContext.mapCenter.y;
        double x = mappoint.x - markerContext.mapCenter.x;

        _points.add(mappoint);

        if (mapPath!.isEmpty())
          mapPath!.moveTo(x, y);
        else
          mapPath!.lineTo(x, y);
      });
      mapPath!.close();
      _leftUpperX = markerContext.mapCenter.x;
      _leftUpperY = markerContext.mapCenter.y;
    
    if (fill != null) mapCanvas.drawPath(mapPath!, fill!);
    if (stroke != null) mapCanvas.drawPath(mapPath!, stroke!);

**Comment by pamtbaau** [comment]
Just curious... Isn't PathMarker just the same as a "PolygonMarker"?

Using the following code:
```
final path = PathMarker(
        strokeWidth: 5,
        strokeColor: 0xFFFF0000,
        displayModel: DisplayModel(),
      );

      for (final cookie in _controller.cookieList) {
        path.addLatLong(cookie);
      }

 _cookieTrailDataStore.addMarker(path);

```
