### ISSUE TITLE
Sorting of indoor level bar reversed

### ISSUE THREAD

**Issue by mikes222** [mikes222/mapsforge_flutter#21]
@Robbendebiene could you please check if it is correct that the sorting of the levels are reversed now. If not please create a testcase and correct the sorting.

![grafik](https://user-images.githubusercontent.com/2129663/120891297-15a36580-c608-11eb-9503-81ba31df4619.png)

**Comment by Robbendebiene** [comment]
Thanks for catching that. Actually levels should always be sorted from positive to negative (descending). I'll fix that.
