### ISSUE TITLE
Adding a map file folder to the example app

### ISSUE THREAD

**Issue by Davomat** [mikes222/mapsforge_flutter#35]
@mikes222
Hi there,
currently some of the the exemplary map files in the example app are stored in private clouds, e.g. google drive. In consultation with Robbendebiene we suggest creating a folder for these map files to store them within this repo as they don't take up much space. We propose to put them into a path like master/maps/ or master/example/assets/map_files/.

Is that fine with you?
If so, which path do you prefer/suggest?

**Comment by mikes222** [comment]
If the files are not too big you can store them at master/example/map_files. Do not use the asset folder since the files will be packed to the APP. 
For bigger files I can store them at my servers.

**Comment by Davomat** [comment]
Thank you for the advice. The files have various sizes:
1,7 MB - Chemnitz - University (Indoor) [Chemnitz Uni Gebäude.map]
0,1 MB - Chemnitz - Library (Indoor) [indoorUB-ext.map]
14  MB - Paris - Louvre (Indoor) [Louvre.map]
1,2 MB - Meadowhall Shopping Center
2,5 MB - Northglenn High School

That are 19 MB in total, is this too much for the repo?

**Comment by mikes222** [comment]
sounds fine to me.
