### ISSUE TITLE
Testing on iPhone

### ISSUE THREAD

**Issue by Davomat** [mikes222/mapsforge_flutter#37]
Has anyone tested the example app with an apple device lately?
I just tested it with an Android phone and in a browser (Chrome). But I would like to know, if there is any issue on apple devices.

**Comment by mikes222** [comment]
Not yet. Feel free to test it and create a pull request if there are changes needed. I expect a few needed changes for the filehandling. Since most of the filehandling is already in the ``FileMgr`` I assume this should not be a big deal.

**Comment by mikes222** [comment]
See #55. Seems it is working for iPhones already. Therefore I close this issue.
