### ISSUE TITLE
How to get clicked location?

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#40]
When we tap once on map, it shows a popup with latitude and longitude for 'example' app. I have to get tapped location instead show it, how to do this?

**Comment by mikes222** [comment]
I do not get what you intend to do. Can you further specify what you want? Some mockup or more detailed explanation?

**Comment by baranacikgoz** [comment]
I am going to do an app that an employee will click it's current location on the map and app will start recording current locations rssi, wi-fi values etc. and will send them to back-end. So i have to get that point's lat-long infos. I'll send it like that,

For a single point
{
-lat
-long
-rssi
-wi-fi
}

**Comment by baranacikgoz** [comment]
for example i am standing in room 151 in a hotel and i will click here on map, and this data will go the back-end
{
-36.898424
-30.647787
-rssi = -60
-wifi= .....
}
like that

**Comment by mikes222** [comment]
The contextMenu is built by ``DefaultContextMenu``. There you have a ``TapEvent`` which contains the coordinates in lat/lon as well as x/y where the user tapped at the map. 
Overwrite ``DefaultContextMenu`` and implement your own behavior. Implement a new ``ContextMenuBuilder`` to instantiate your own contextMenu. Then add the new ContextMenuBuilder to the ``ViewModel``

**Comment by baranacikgoz** [comment]
Thanks a lot it will very helpfull.
