### ISSUE TITLE
Documentation is weak for people who are not flutter expert.

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#44]
I am keeping an eye on this repository for 4~ months. Appreciate for the work you've done. I think it's the only package for who wants to use their own compiled indoor maps. But there are someone who is not an expert flutter dev. like me. And I found these documentations hard to understand. The instructions on the `README` are not similar with your `example` app. And your codes which are in the `README` are not clear. Since people like me may can't figure out where to put these codes, I even think that should I put these codes in setState or initState or somewhere else etc. Another simple example you wrote `MapFile mapFile = MapFile(_localPath + "/" + mapfile, null, null);` in `README` but there is not a constructor `MapFile()`, there are `MapFile.from` and `MapFile.using` etc. and which one should we use? Even these are not clear. I would see an example with your codes in `README` in a single `.dart` file. Your example app has many folders & files and hard to understand how to use them. I am trying to solve this map thing in a single `.dart` file which is `show_map.dart`. I followed the instructions but always get some error due to they are unclear.  

This is my code and I am always getting `lateInitializeErrror: xxxx has not been initialized`. Where and how to put these codes? Am I doing it right?

My Code;

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:mapsforge_flutter/core.dart';
import 'package:mapsforge_flutter/maps.dart';

class ShowMap extends StatefulWidget {
  @override
  _ShowMapState createState() => _ShowMapState();
}

class _ShowMapState extends State<ShowMap> {
  late MapFile mapFile;
  late SymbolCache symbolCache;
  GraphicFactory graphicFactory = const FlutterGraphicFactory();
  DisplayModel displayModel = DisplayModel();
  late RenderThemeBuilder renderThemeBuilder;
  late String content;
  late RenderTheme renderTheme;
  late MapDataStoreRenderer jobRenderer;
  late MapModel mapModel;
  late ViewModel viewModel;

  start() async {
    mapFile = await MapFile.from("assets/maps/akuzem.map", null, null);

    content = await rootBundle
        .loadString("assets/maps/render_themes/defaultrender.xml");

    setState(() {});
  }

  @override
  void initState() {
    super.initState();
    start();

    jobRenderer =
        MapDataStoreRenderer(mapFile, renderTheme, graphicFactory, true);

    mapModel = MapModel(
      displayModel: displayModel,
      renderer: jobRenderer,
    );

    symbolCache = FileSymbolCache(rootBundle);

    renderThemeBuilder =
        RenderThemeBuilder(graphicFactory, symbolCache, displayModel);

    renderThemeBuilder.parseXml(content);

    renderTheme = renderThemeBuilder.build();

    viewModel = ViewModel(displayModel: displayModel);
  }

  @override
  Widget build(BuildContext context) {
    return FlutterMapView(
        mapModel: mapModel,
        viewModel: viewModel,
        graphicFactory: graphicFactory);
  }
}

```

**Comment by mikes222** [comment]
Good to know. My suggestion? Put here a list of problems in the docu along with the type of problem and I will try to tackle them step by step by enhancing/correcting the docu and explaining the behavior. 

On the other hand it is always welcome to create PullRequests if you would like to change/enhance source or docu by yourself so that everyone including my can benefit from it. That is (at least my) core motivation of publishing a library as open source.

**Comment by baranacikgoz** [comment]
You are a hero. First of all I find the doc. about compiling maps josm to .map etc. is magnificent. However I am having difficulties in applying the codes in `README`.  

Since you are capable of writing packages, expert in other words. Maybe you don't look from people point of view who are new to flutter . Therefore me asking these maybe look dumb. But I really tried for a while . 

So I would appreciate if you make these clean. 

- Where should we put these codes? I mean all the codes in ```README```, where to put them? Like under the widget class as properties, or in setState or in initState or something else etc.?

A simple example is that for some reason I am unable to write `await mapFile.init();`. I think this is because I don't know where to write it.

Since I don't know where to put codes, wrote them like this;  
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:mapsforge_flutter/core.dart';
import 'package:mapsforge_flutter/maps.dart';

class ShowMap extends StatefulWidget {
  @override
  _ShowMapState createState() => _ShowMapState();
}

class _ShowMapState extends State<ShowMap> {
  late MapFile mapFile;
  late SymbolCache symbolCache;
  GraphicFactory graphicFactory = const FlutterGraphicFactory();
  DisplayModel displayModel = DisplayModel();
  late RenderThemeBuilder renderThemeBuilder;
  late String content;
  late RenderTheme renderTheme;
  late MapDataStoreRenderer jobRenderer;
  late MapModel mapModel;
  late ViewModel viewModel;

  start() async {
    mapFile = await MapFile.from("assets/maps/akuzem.map", null, null);

    content = await rootBundle
        .loadString("assets/maps/render_themes/defaultrender.xml");

    setState(() {});
  }

  @override
  void initState() {
    super.initState();
    start();

    jobRenderer =
        MapDataStoreRenderer(mapFile, renderTheme, graphicFactory, true);

    mapModel = MapModel(
      displayModel: displayModel,
      renderer: jobRenderer,
    );

    symbolCache = FileSymbolCache(rootBundle);

    renderThemeBuilder =
        RenderThemeBuilder(graphicFactory, symbolCache, displayModel);

    renderThemeBuilder.parseXml(content);

    renderTheme = renderThemeBuilder.build();

    viewModel = ViewModel(displayModel: displayModel);
  }

  @override
  Widget build(BuildContext context) {
    return FlutterMapView(
        mapModel: mapModel,
        viewModel: viewModel,
        graphicFactory: graphicFactory);
  }
}
```

- Your code is not executable. I mean you instantiate from an abstract class in your code like `SymbolCache symbolCache = SymbolCache(rootBundle);` And neither there is no explanation of which one should we use `FileSymbolCache` or `MemorySymbolCache` etc. nor I don't see it.

- Example app is complicated. I mean there is so much file in it and it is not matching the code in ```README```. For example there is `MapDataStore` in the example there is not in ```README```. I even think that: "Do I have to mix these example app codes with README codes or they are different ways of doing this?" "Do I have to have this much of files, can I handle map thing in one file?" etc..

- (If they are different ways of doing this) Can you show the best practices of README codes from my code, or can you provide an example code of the working version of README codes?

Thanks in advance.

**Comment by baranacikgoz** [comment]
You are a hero. First of all I find the doc. about compiling maps josm to .map etc. is magnificent. However I am having difficulties in applying the codes in `README`.  

Since you are capable of writing packages, expert in other words. Maybe you don't look from people point of view who are new to flutter . Therefore me asking these maybe look dumb. But I really tried for a while . 

So I would appreciate if you make these clean. 

- Where should we put these codes? I mean all the codes in ```README```, where to put them? Like under the widget class as properties, or in setState or in initState or something else etc.?

A simple example is that for some reason I am unable to write `await mapFile.init();`. I think this is because I don't know where to write it.

Since I don't know where to put codes, wrote them like this;  
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:mapsforge_flutter/core.dart';
import 'package:mapsforge_flutter/maps.dart';

class ShowMap extends StatefulWidget {
  @override
  _ShowMapState createState() => _ShowMapState();
}

class _ShowMapState extends State<ShowMap> {
  late MapFile mapFile;
  late SymbolCache symbolCache;
  GraphicFactory graphicFactory = const FlutterGraphicFactory();
  DisplayModel displayModel = DisplayModel();
  late RenderThemeBuilder renderThemeBuilder;
  late String content;
  late RenderTheme renderTheme;
  late MapDataStoreRenderer jobRenderer;
  late MapModel mapModel;
  late ViewModel viewModel;

  start() async {
    mapFile = await MapFile.from("assets/maps/akuzem.map", null, null);

    content = await rootBundle
        .loadString("assets/maps/render_themes/defaultrender.xml");

    setState(() {});
  }

  @override
  void initState() {
    super.initState();
    start();

    jobRenderer =
        MapDataStoreRenderer(mapFile, renderTheme, graphicFactory, true);

    mapModel = MapModel(
      displayModel: displayModel,
      renderer: jobRenderer,
    );

    symbolCache = FileSymbolCache(rootBundle);

    renderThemeBuilder =
        RenderThemeBuilder(graphicFactory, symbolCache, displayModel);

    renderThemeBuilder.parseXml(content);

    renderTheme = renderThemeBuilder.build();

    viewModel = ViewModel(displayModel: displayModel);
  }

  @override
  Widget build(BuildContext context) {
    return FlutterMapView(
        mapModel: mapModel,
        viewModel: viewModel,
        graphicFactory: graphicFactory);
  }
}
```

But it always return `lateInitializationError: xxxx has not been initalized`

- Your code is not executable. I mean you instantiate from an abstract class in your code like `SymbolCache symbolCache = SymbolCache(rootBundle);` And neither there is no explanation of which one should we use `FileSymbolCache` or `MemorySymbolCache` etc. nor I don't see it.

- Example app is complicated. I mean there is so much file in it and it is not matching the code in ```README```. For example there is `MapDataStore` in the example while there is not in ```README```. I even think that: "Do I have to mix these example app codes with README codes or they are different ways of doing this?" "Do I have to have this much of files, can I handle map thing in one file?" etc..

- (If they are different ways of doing this) Can you show the best practices of README codes from my code, or can you provide an example code of the working version of README codes?

By the way, I am planning to have the map in local files like assets, not fetching from a server, is it possible?

Thanks in advance.

**Comment by mikes222** [comment]
Thx for your insights. I will take the time soon and try to update the docu accordingly. 
Regarding having local files in assets, in principle this is possible. But it should be used for small files only. Otherwise your app will quickly blew up and exceeds the max filesize for apps (at least for android).
