### ISSUE TITLE
Tap event

### ISSUE THREAD

**Issue by mirecta** [mikes222/mapsforge_flutter#45]
How can i disable Tap event , i a dont want floating bubble with position

**Comment by mikes222** [comment]
Make sure that ``ViewModel.contextMenuBuilder`` is ``null``

**Comment by mirecta** [comment]
i has ViewModel(displayModel: displayModel, contextMenuBuilder: null); bit after tap i see green bubble with position 
![Screenshot_1644657747](https://user-images.githubusercontent.com/1140680/153705537-239e1b9e-9aea-4589-aa78-c8441e578e9c.png)
