### ISSUE TITLE
Map file and style switch 

### ISSUE THREAD

**Issue by mirecta** [mikes222/mapsforge_flutter#46]
It is possible switch MapFile and MapStyle on demand ?

**Comment by mikes222** [comment]
For ``MapFile`` consider using ``MultiMapDataStore``. What do you mean with MapStyle? There is no such class in Mapsforge

**Comment by mirecta** [comment]
sry for wrong the second i mean switch render style on demand . choose another xml an apply it

**Comment by mikes222** [comment]
sure, this is possible. You need to provide another rendertheme. See also the ``renderkey`` property which is used in several classes like FileTileBitmapCache to distinguish between different renderthemes.
