### ISSUE TITLE
Tap event still not dsappear even if contextMenuBuilder is null

### ISSUE THREAD

**Issue by mirecta** [mikes222/mapsforge_flutter#47]
i has ViewModel(displayModel: displayModel, contextMenuBuilder: null); but after tap i still see green bubble with position 
![image](https://user-images.githubusercontent.com/1140680/153705733-45fc8238-dc49-4c8d-8608-edfe11cfa703.png)

_Originally posted by @mirecta in https://github.com/mikes222/mapsforge_flutter/issues/45#issuecomment-1037083658_

**Comment by mikes222** [comment]
Please use the most current version from github while developing. 
in ``pubspec.yaml`` change the reference to mapsforge:

        git: https://github.com/mikes222/mapsforge_flutter/tree/master/mapsforge_flutter

or (if you already downloaded your own copy) use something like this:

      mapsforge_flutter:
        path: ../../github_mapsforge_flutter/mapsforge_flutter
