### ISSUE TITLE
Is it possible to add event based icons/markers on map ?

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#50]
We are measuring ble data respect to the location. What I wanted to do is, when I click `end measuring`, Want to put there an icon/marker that shows I have already measured that point. Here is what I talk about : 

https://user-images.githubusercontent.com/52239507/158404341-10d4d249-c5a9-48f8-8eea-c11d092978ca.mp4

By the way, I've separated your package's view folder and put it in my package's lib folder (in order to gain more controll on defaultContextMenu, add map screen my custom appBar and etc.). And made two package depends each other by adding my package's pubspec.yaml file
```
mapsforge_flutter:
    path: packages/mapsforge_flutter
```
  
and your package's pubspec.yaml file 
```
mapping_tool:
    path:
      ../../../mapping_tool
```  
Mapping tool is the name of our application. The folder structure is (your package's view folder is under my package's lib/core/map/):  
![folder_structure2](https://user-images.githubusercontent.com/52239507/158406247-ee79ed41-4e2f-400f-8eea-7a1eba81c6c0.png)

 And we are using BloC for state management so maybe I can handle this adding icon/marker thing with BloC. These information is just to make question easily answerable. Thanks in advance.

**Comment by mikes222** [comment]
The suggested way to do this is:
- Create a MarkerDatastore and add it to the ``MapModel``
- At the ``end measuring`` event add a new marker (e.g. a ``PoiMarker``) to the datastore
- call ``markerDatastore.setRepain()`` to trigger repainting the datastore

That's all. 

Enhancement: You could also consider adding a ``PathMarker`` to the datastore and add the path as the user walks around.

**Comment by mikes222** [comment]
btw. if you miss features which may be of interest for others please add them, create a testcase and commit them to this project via a PullRequest. We all want to participate from your enhancements.

**Comment by baranacikgoz** [comment]
Where can i add markerDataStore, in which specifi file? In ```mapview.dart``` or somewhere else?

**Comment by baranacikgoz** [comment]
I've added some code into ```map-view-page.dart``` in order to just show any marker before go further. But any marker shows up :(

```
/// Constructs the body ([FlutterMapView]) of the [MapViewPage].
  Widget _buildMapViewBody(BuildContext context) {
    return FutureBuilder(
        future: widget.mapFileData.isOnlineMap == ONLINEMAPTYPE.OFFLINE
            ? _prepareOfflineMap(widget.mapFile!)
            : _prepareOnlinemap(),
        builder: (context, AsyncSnapshot snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (viewModel == null) {
            // not yet prepared
            return const Center(child: CircularProgressIndicator());
          }


          MarkerDataStore markerDataStore = MarkerDataStore();
          markerDataStore.addMarker(PoiMarker(
              src: "lib/core/map/assets/icons/elevator.svg",
              height: 20,
              width: 20,
              latLong:
                  const LatLong(AkuzemMap.initialLat, AkuzemMap.initialLong)));

          mapModel!.markerDataStores.add(markerDataStore);


          return FlutterMapView(
            mapModel: mapModel!,
            viewModel: viewModel!,
            graphicFactory: _graphicFactory!,
          );
        });
  }

```
