### ISSUE TITLE
contextMenu not appears after update

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#51]
I've pulled your latest commits and default context menu isnot showing when tapped on map. To be sure i've built your example app too. The same.

**Comment by mikes222** [comment]
Sorry, I am in the process of refactoring the markers to make them faster. I  will check in now. It should work again then. Please expect an forthcoming api change in the tapped() method of the markers.

**Comment by baranacikgoz** [comment]
Ok no problem. Appreciate your work. Still waiting for default context menu to open. It still not working when i randomly tap on map, while it was working before :(

**Comment by mikes222** [comment]
It should work now after the latest commit. Please close this issue after verification.

**Comment by baranacikgoz** [comment]
Working properly, huge thanks
