### ISSUE TITLE
Where to add marker related codes?

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#52]
Where and how to add marker to map. I know you've stated that it should be included in mapModel's markerDataStore but regarding your example app can you give me example code  to add marker? I've tried this at the end of the ```map-view-page2.dart``` in ```_createOnlineMapModel()``` and it didn't work.  Any marker showed up on map.

```
MarkerDataStore markerDataStore = MarkerDataStore();
    markerDataStore.addMarker(BasicPointMarker(
        latLong: const LatLong(AkuzemMap.initialLat, AkuzemMap.initialLong)));

    /// Now we can glue together and instantiate the mapModel and the viewModel. The former holds the
    /// properties for the map and the latter holds the properties for viewing the map
    MapModel mapModel = MapModel(
      displayModel: displayModel,
      renderer: jobRenderer,
      tileBitmapCache: bitmapCache,
    );

    mapModel.markerDataStores.add(markerDataStore);

    return mapModel;
```

**Comment by mikes222** [comment]
I have now implemented a demo for using markers (for offline maps only). Hope this helps you to understand how it works. The code above looks good and should also work btw.

**Comment by baranacikgoz** [comment]
Huge thanks. Managed to add markers on my map after latest commit. You're a hero !
