### ISSUE TITLE
Android 5.1.1 phone can't download map

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#53]
Everything works fine with 7 and 12 (at least I've tried these) but 5.1.1 phone can't download map. And there is nothing in debug console.  Any idea? Btw I know this issue is probably not related with your package but the only solution I saw on internet was adding ```<uses-permission android:name="android.permission.INTERNET"/>``` in ```AndroidManifes.xml``` but it didn't help.  
![WhatsApp Image 2022-03-25 at 16 17 06](https://user-images.githubusercontent.com/52239507/160135162-328cc838-02da-41ec-83ae-d5c9f43ce54d.jpeg)

**Comment by mikes222** [comment]
Mapsforge itself does not download anything. Though I would like to solve world-problems it seems I am unable to do so :-) I would check if you really need to support Android 5 since this is such an old O/S with minor market share.

**Comment by baranacikgoz** [comment]
Thanks for advice. I was just trying to learn what is the minimum android version can my app supports. Seems 5 is not one of them. Closing issue, thanks again :))
