### ISSUE TITLE
You should consider migrating to very_good_analysis or sth like that.

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#56]
Package is so useful, but it has over 2-3K+ linting warnings including not typing const or final which cause performance issues. I am sure that the performance of package will change massively if you obey linting rules. I suggest you use standard dart linter or if you want to use an advance linting thing: [very_good_analysis](https://pub.dev/packages/very_good_analysis). Therefore your code will be sync dart standards and others can make pull requests easily moreover increase performance. From my view, even if I try to contribute this repository I can't because your code is very very different than it should be. If you want me to migrate whole repository to very_good_analysis, I will try my best. Because this is a super useful package and I love it.

**Comment by mikes222** [comment]
Sure, feel free to create PR. If you think that the rules makes sense and does not overannoy the developers it would be nice to have them implemented. I have already implemented a couple of linter rules where I thought it would make sense. See ```https://github.com/mikes222/mapsforge_flutter/blob/master/mapsforge_flutter/analysis_options.yaml``` for more informations
