### ISSUE TITLE
Issues in 'Getting Started' in README

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#59]
As a followup on issue [#44](https://github.com/mikes222/mapsforge_flutter/issues/44) about the documentation, I decided to walk through the README and provide some feedback.

#### Feedback on README.md

- Load the mapfile:
  ```dart
  // 1. IDE shows error: The class 'MapFile' doesn't have an unnamed constructor.
  // 2. MapFile constructor returns a Future. `await` is required.
  MapFile mapFile = MapFile('/path/to/berlin.map', null, null);
  // 3. IDE shows error: The method 'init' isn't defined for the type 'MapFile'.
  await mapFile.init();
- Create the cache for assets
  ```dart
  // 4. IDE shows error: Abstract classes can't be instantiated.
  SymbolCache symbolCache = SymbolCache(rootBundle);
  ```
- Create the graphicFactory: No issues
- Create the displayModel: No issues
- Create the render theme
  ```dart
  // 5. RenderThemeBuilder requires 3 parameters
  RenderThemeBuilder renderThemeBuilder = RenderThemeBuilder(graphicFactory, displayModel);
  
  // 6. Theme location should be 'assets/render_themes/defaultrender.xml'
  String content = await rootBundle.loadString("assets/defaultrender.xml");
  
  // 7. IDE shows error on parseXml. `await` is not needed.
  await renderThemeBuilder.parseXml(content);
  RenderTheme renderTheme = renderThemeBuilder.build();
  ```
- Create the Renderer: No issues
- Glue everything together into two models.
  ```dart
  // 8. IDE shows issue: Parameters graphicsFactory and symbolCache are not defined 
  MapModel mapModel = MapModel(
    displayModel: displayModel,
    graphicsFactory: graphicFactory,
    renderer: jobRenderer,
    symbolCache: symbolCache,
    tileBitmapCache: bitmapCache,  
  );

  ViewModel viewModel = ViewModel(displayModel: displayModel);
  ```
- In your build() method of the widget include the mapView:
  ```dart
  // 9. Missing parameter
  // 10. Variables `mapModel`, `viewModel` and `graphicFactory` defined above, should have been class properties
  FlutterMapView( mapModel: mapModel, viewModel: viewModel, ),
  ```

**Comment by vedranivicatos** [comment]
I have struggled with the documentation/Readme myself as it seems a bit outdated since there were some code changes. You can follow the example code provided in [simplified_example/lib/main.dart](https://github.com/mikes222/mapsforge_flutter/blob/master/simplified_example/lib/main.dart). I believe that piece of code is up-to-date with latest changes. I can also provide you with some code I used myself if needed. You are welcome to make changes and PR to the README file/docs.

**Comment by pamtbaau** [comment]
@vedranivicatos, Thanks for pointing me to my own sample code... :-)

**Comment by vedranivicatos** [comment]
@pamtbaau Lmao yeah, I realised in the meantime but decided to leave it here if someone comes across looking for some example code as I did.

**Comment by mikes222** [comment]
Updated the docu now according to your suggestions. Feel free to create PRs if you want to add/modify something.
