### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by grait** [mikes222/mapsforge_flutter#6]
Dear mikes222,

I write you through this issue, because I couldn't find any other contact address.

We have a small developer group at Chemnitz University of Technology that wants to develop a cross platform app for indoor/outdoor navigation using OSM and its Simple Indoor Tagging schema.

I just want to ask you whether you are still maintaining this project. If yes, then we would like to send our pull requests to this repo :-)

For further information about our project feel free to contact me at thomas.graichen@etit.tu-chemnitz.de

Best regards, Thomas

**Comment by mikes222** [comment]
Just to document that issue: We are in contact with each other via mail. This project is of course still active and everyone is invited to contribute.

**Comment by moovida** [comment]
Thanks for this update. I am currently a big big fan of this project, but unable to directly contribute code. But I would love to hear about updates. Keep up the fantastic work!
I can do a lot of testing if this can help :-)
