### ISSUE TITLE
Difference in rendering quality of same map using original Mapsforge lib and mapsforge_flutter

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#61]
I've used a Mapsforge map of [Berlin](http://ftp-stud.hs-esslingen.de/pub/Mirrors/download.mapsforge.org/maps/v5/europe/germany/berlin.map) in two applications:
- A mobile Android/Kotlin app using the original Mapsforge library.
- A Windows 11 desktop app using mapsforge_flutter library. See PR [#60](https://github.com/mikes222/mapsforge_flutter/pull/60)

Here are two screenshots to show the difference:

**Android with original Mapsforge**

![MapsForge-Android-Java](https://user-images.githubusercontent.com/5120011/174678941-8aa4de90-7fcc-43a4-9697-3f114bcc2abf.png)

**Windows 11 desktop using mapsforge_flutter**

![MapsForge-Flutter-Win11](https://user-images.githubusercontent.com/5120011/174678999-1bfb5a7b-6cd5-4086-8be7-24a07cbb54c4.png)

**Quality**
- The quality of the map shown by the flutter app, isn't that crisp.
- It feels as if the flutter app shows image titles instead of svg, considering the jacked appearance of lines. Also the text are displayed quite blurred.

**Rendering of elements**
- Since elements are displayed quite differently, and service roads (the fat black lines) are displayed really off, I thought it might just be a matter of xml theme files. I've copied the theme files used by Mapsforge into the flutter desktop app, but unfortunately, the app crashes on each an every original theme..

Any feedback, thoughts or suggestions?

**Comment by mikes222** [comment]
Please give me the coordinates of this map (lat/lon/zoom) and a link to the "theme file used by Mapsforge".

**Comment by pamtbaau** [comment]
Here is the link on openstreetmap.org: https://www.openstreetmap.org/#map=17/52.52200/13.39090
Coords: 52.52278, 13.38982
Zoom: 16-17

MapsForge themes: https://github.com/mapsforge/mapsforge/tree/master/mapsforge-themes/src/main/resources/assets/mapsforge
I've tried both themes.

**Comment by mikes222** [comment]
Mapsforge can now read the default renderthemes without errors.

**Comment by mikes222** [comment]
Support for serif fonts (Monbijoupark) implemented

**Comment by mikes222** [comment]
It is still a long road:
- Improve labels for polygons (streets)
- Support for larger tiles (256*256px is currently the only one supported)
- support for screen pixels-to-logical pixels scaling

All of these tasks may take a lot of work so do not expect to have the solution soon.

**Comment by pamtbaau** [comment]
I appreciate your hard work, but don't work too hard to just fix this issue unless you see it as a base requirement that mapsforge_flutter renders a map exactly the same as the original Mapsforge Android library does.

The project I was working on has got other priorities. So no worries on my side.

**Comment by pamtbaau** [comment]
I've looked at the new Berlin map using the original theme in the example app. Quite an improvement!

Thank you!
