### ISSUE TITLE
Improve scrolling/zooming performance

### ISSUE THREAD

**Issue by vedranivicatos** [mikes222/mapsforge_flutter#62]
#### Flutter version:
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (6 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

#### Plugin version: 
**2.0.2** using:
```
  mapsforge_flutter:
    git:
      url: https://github.com/mikes222/mapsforge_flutter
      path: mapsforge_flutter
```

#### Device:
Apple iPhone 11, physical device, **iOS** 15.5

### **Description**
When swipe/flick scrolling the map view the rendering lags quite a bit. Also, when pinch zooming the lag is noticeable and the markers are not properly scaled until the pinch is finished. I would like to make these improvements if possible and make a PR to contribute so I would like to know if this can be done, what are the required steps or some suggestions to nudge me in the right direction?

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/106805181/174797084-7db142ae-365d-45a3-9386-a67c5cccc904.gif)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/106805181/174797188-bce05a3d-7db1-4faa-83e1-ff77ada9349a.gif)

**Comment by mikes222** [comment]
currently working at other issues. This is still on my list...

**Comment by mikes222** [comment]
I have checked in now the first version to support better image quality. If you want to test it, change the displayModel and set DisplayModel(deviceScaleFactor: 2);. I have not yet tested it with other factors. Still need to test some markers (circleMarker is already working).
Changes made:

-     Image of the tiles are improved
-     pinch2zoom also affects markers
-     more gesture detections (click, double-click, long-click, hold-then-move)

Feedback and error reports are welcome.

**Comment by zmesingeratos** [comment]
Hi, I have tested version 2.0.2 of plugin and I am having issues with laggy map, loading map tiles and markers.

**This is my flutter version:**

- Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
- Framework • revision e3c29ec00c (8 weeks ago) • 2022-09-14 08:46:55 -0500
- Engine • revision a4ff2c53d8
- Tools • Dart 2.18.1 • DevTools 2.15.0

**Device is**:
Apple iPhone 11, physical device, iOS 15.5

**Description**
I am having several issues. When I pinch out, map tiles are not loading until I stop pinching. Further, flicking through the map is laggy. Also, markers are not scaled until I stop zooming in/out. Good thing is that markers are staying where they should while zooming in/out and that map looks sharper when zooming in. 

**These are the parts of code that I think are relevant to these issues:**

**MapModel:**
``` 
MapModel mapModel = MapModel(
      displayModel: _displayModel,
      renderer: jobRenderer,
      symbolCache: _symbolCache,
      tileBitmapCache: await FileTileBitmapCache.create(jobRenderer.getRenderKey()),
      // tileBitmapCache: bitmapCache,
    );
```
**ViewModel:**
``` 
ViewModel viewModel = ViewModel(
      displayModel: _displayModel,
      contextMenuBuilder: null,
      // contextMenuBuilder: DistanceContextMenuBuilder()
    );
```
**DisplayModel:**
``` 
  DisplayModel _displayModel = DisplayModel(deviceScaleFactor: 2.0);
```
**Usage of FlutterMapview:**
``` 
return FutureBuilder<MapModel>(
            future: _createMapModel(),
            builder: (context, snapshot) {
              if(snapshot.hasData) {
                return FlutterMapView(mapModel: snapshot.data!, viewModel: _createViewModel());
              }else{
                return Container();
              }
            }
          );
```

**Usage of CircleMarker:**
```
_markers[senderUri] = CircleMarker(
        center: LatLong(
        latitude,
        longitude,
    ),
        fillColor: 0xFF000000,
        displayModel: _displayModel);
```

**Here is the gif of markers scaling not working and map tiles not loading:**

![ezgif com-gif-maker-2](https://user-images.githubusercontent.com/117817522/200831474-ac21c1c0-a931-4b3a-acb1-a06e82a92113.gif)

**Here is the gif of map flick that is laggy:**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/117817522/200831664-c8705f45-fa98-47a5-af47-be9a1d45cc35.gif)
