### ISSUE TITLE
Can you guide us for making browser based map drawing & editing tool like josm with mapsforge. 

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#63]
Hi, we want to make a browser based map drawer, editor like josm with mapsforge flutter. I have no idea yet but thought putting markers on map and get their absolute position, then connect them together to make a room etc. and  process this positions and keys on backend and generate osm file again respect to changes. I bet you have better ideas than mine. Can't wait to listen.

**Comment by mikes222** [comment]
We have polygonmarkers already. Seems you need to create poimarker for each corner and polygonmarker to connect the corners. I guess you also need drag'n'drop so you need to enhance the GestureDetector. Writing OSM files are a totally different topic however.

**Comment by baranacikgoz** [comment]
Thanks a lot. We're working on it. I am planning to integrate an example editor here with pull requests when we're finished. It will take long time I guess.
