### ISSUE TITLE
Can we get room, corridor, etc. information from tapped location?

### ISSUE THREAD

**Issue by baranacikgoz** [mikes222/mapsforge_flutter#69]
I need your thoughts about getting rooms, corridors, stairs, etc from tapped location on the map. Does the package provide that information somewhere maybe I missed it? 

First, I am asked to get more information about the tapped location on the map. As far as I know, we can get level, lat, long right now.

Does it make sense to use a script to get information from .osm files like rooms, corridors, pois, etc? I mean is it worth writing a script that scans this data:
````
  <way id='-101974' action='modify' visible='true'>
    <nd ref='-102078' />
    <nd ref='-102079' />
    <nd ref='-102080' />
    <nd ref='-102081' />
    <nd ref='-102078' />
    <tag k='indoor' v='room' />
    <tag k='level' v='0' />
    <tag k='name' v='manager office' />
  </way>
```` 

and send a JSON to the backend like this:
````
{
    "type": "room",
    "name": "manager office",
    "indoor_level": "0",
    "coordinates": [36.12314, 36.123466, 36.1234123, 36.1342, 36.234425]
````

and then when I tapped that location on the map I knew which room is it thanks to JSON above. Am I missing something or is this logically true?

**Comment by mikes222** [comment]
take a look at the example app in the folder debug. I have created a method to fetch the information of the current tile from the map and display it via a datastore. I guess it is somehow what you need.

**Comment by baranacikgoz** [comment]
Thanks a lot
