### ISSUE TITLE
relativePathPrefix issues

### ISSUE THREAD

**Issue by moovida** [mikes222/mapsforge_flutter#71]
Hello, I have been finally able to upgrade to the latest version and I am having problems with the case in which we use external themes (ex for contour lines). 
For these I used to pass the path to the folder in which the theme svg would be. With this last release it is not possible to me anymore.

I am attaching a debug session on linux, because I can better explain.

![image](https://user-images.githubusercontent.com/390250/189357557-86fab6ab-91ef-4fb5-965b-4789ea3a4d3c.png)

In my case I used to pass the absolute path. This is something I can change to relative, but as you can see, the path coming from:
```
FileHelper.findLocalPath()
```
is completely different from the one in which my data resides (hence ending in a path duplication). 

Do you think there would be a possibility to allow also for absolute paths to be passed to avoid this? Something like: FileSymbolCache.withAbsolutePathPrefix ?

What do you think?
Thank you

**Comment by mikes222** [comment]
The code you mention is in ```FileSymbolCache```. I see two possiblities: The easier is to overwrite ```SymbolCache``` or the mentioned ```FileSymbolCache``` and create your own implementation.

The better method is to move the loading of symbols to its own class (since the code is duplicated between ```FileSymbolCache``` and ```MemorySymbolCache```).

I have done now the latter for you. Please pull the newest sources from github and use the imageLoader like so:

    FileSymbolCache(
                imageLoader: ImageAbsoluteLoader(absolutePathPrefix: "/path/to/file"));

**Note**: Drawback is that the FileSymbolCache constructor has been changed now. Sorry for that.

If there are still problems feel free to create a PullRequest or ask me.

**Comment by moovida** [comment]
Dear @mikes222, thanks a ton for the fix. I made a few lines of fix to it, because it was trimming too early, leaving the colon.

Here is my code, it contains also a few checks on missing / and removes possible relative prefixes that andromap xmls can contain:

```
class ImageAbsoluteLoader implements ImageLoader {
  static final String PREFIX_JAR = "jar:";

  static final String PREFIX_JAR_V1 =
      "jar:/org/mapsforge/android/maps/rendertheme";

  static final String PREFIX_FILE = "file:";

  final String absolutePathPrefix;

  const ImageAbsoluteLoader({required this.absolutePathPrefix});

  ///
  /// Returns the content of the symbol given as [src] as [ByteData]. This method reads the file or resource and returns the requested bytes.
  ///
  @override
  Future<ByteData?> fetchResource(String src) async {
    // compatibility with mapsforge
    if (src.startsWith(PREFIX_JAR)) {
      src = src.substring(PREFIX_JAR.length);
      src = "packages/mapsforge_flutter/assets/" + src;
    } else if (src.startsWith(PREFIX_JAR_V1)) {
      src = src.substring(PREFIX_JAR_V1.length);
      src = "packages/mapsforge_flutter/assets/" + src;
    } else if (src.startsWith(PREFIX_FILE)) {
      var index = src.lastIndexOf("/");
      if (index > 0) {
        src = src.substring(index);
      } else {
        src = src.substring(PREFIX_FILE.length);
      }
    }
    if (!absolutePathPrefix.endsWith("/")) {
      src = "/" + src;
    }
    src = absolutePathPrefix + src;
    File file = File(src);
    if (await file.exists()) {
      Uint8List bytes = await file.readAsBytes();
      return ByteData.view(bytes.buffer);
    }
    return null;
  }
}
```

The result is very cool:

![image](https://user-images.githubusercontent.com/390250/189535749-f524b778-5d72-4646-887d-8644a44488e6.png)

and here my first question: there was a scale factor that could be applied, which was taking care of making labels larger. It has been removed now. Is there still a way to allow label scaling? 

At some intermediate zoomlevels I see some green patterns. I have too few knowledge on how internals work, but can it be that isolines are fighting with green areas each for their survival? 

Zoom level before:
![image](https://user-images.githubusercontent.com/390250/189535875-cf978c49-fbb3-445e-918d-099847e28db9.png)
and zoom level after:
![image](https://user-images.githubusercontent.com/390250/189535899-4157ef90-71db-446b-8f1f-dc29b682c280.png)

Sorry for not being able to be more scientific.

**Comment by mikes222** [comment]
For the scalefactor see ```DisplayModel.fontScaleFactor```

**Comment by moovida** [comment]
Thank you!

On a sidenote I am no longer able to make the higher zoomlevels work. I am constantly getting: 

```
flutter: Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
```

I looked like crazy, but have not been able to understand where this happens. And sometimes I get a complain about Tile not being a subtype of string, but I have no place in which I do such a cast. So I am going mad right now.
Will try again tomorrow with clear head. Thanks for you help.

Last question. Is this the right way to get the image:

```
var resultTile = await dataStoreRenderer.executeJob(mapGeneratorJob);
ui.Image img = (resultTile as FlutterTileBitmap).getClonedImage();
```

**Comment by mikes222** [comment]
Please recheck your source:

    var index = src.lastIndexOf("/");

seems you cut off any path and just use the last part of your given path

    if (!absolutePathPrefix.endsWith("/"))

if not ends with then append at the beginning, that seems weird.

**Comment by mikes222** [comment]
Line and hillshading have a property ```level```, the latter also ```layer```. Try playing around with them. 

Regarding the disposed images and the typing problems with Tiles I need to know where it comes from. 

    Future<JobResult> executeJob(Job job);

returns a ```JobResult``` which cannot be casted to a ```FlutterTileBitmap```. This is btw one of the reasons I generally avoid using ```var``` since I do not see the types.

**Comment by moovida** [comment]
> Please recheck your source:
> 
> ```
> var index = src.lastIndexOf("/");
> ```
> 
> seems you cut off any path and just use the last part of your given path

Yes, that is wanted. Andromap packages the themes like this:

![image](https://user-images.githubusercontent.com/390250/189541757-fe629f3e-d4de-4869-840e-6937c7e98559.png)

where elevate is the name of the style used. Then there is a folder ele-res.

The best way I found to make it work, is to extract all data into a folder with the same name of the *.map file (hence the removal of any relative sub-path) and then rename the Elevate.xml also with the same name. 

While I am writing I am not sure what the best for a user would be. And I just checked the andromap themes and they are the Elevate and Elements. So it might be an idea to just support a simple unzipped file extracted nearby the map file. In that case it would be enough the remove the "file:" in front of it and generate the complete path to the svg.

> ```
> if (!absolutePathPrefix.endsWith("/"))
> ```
> 
> if not ends with then append at the beginning, that seems weird.

This is just because if the path doesn't end with /, then the code attaches the relative path of the image to it. If the slash is missing, the path is not valid. It seemed like a worthy check to me, but it can also be something properly documented in the API. No problem for me to remove it and make sure the absolute path ends with slash.

> Line and hillshading have a property `level`, the latter also `layer`. Try playing around with them.
> 
> Regarding the disposed images and the typing problems with Tiles I need to know where it comes from.

Yes, that is also something I would love to know. 

> ```
> Future<JobResult> executeJob(Job job);
> ```
> 
> returns a `JobResult` which cannot be casted to a `FlutterTileBitmap`. This is btw one of the reasons I generally avoid using `var` since I do not see the types.

Ok, that looks odd, will check into that.

**Comment by moovida** [comment]
Sorry, I copied from a piece of code of mine that was not used. The jobresult would expose the bitmap, which then is checked for being a ```FlutterTileBitmap```
```
var resultTile = jobresult.bitmap;
```

**Comment by mikes222** [comment]
Seems you have a very special usecase. I suggest to create your own implementation of ImageLoader and use that implementation instead.

**Comment by moovida** [comment]
You might be right. I will follow your suggestion and if I come up with something with a general sense (like supporting andromaps in general seems a nice idea), then I will follow up. 

In the meanwhile I have narrowed the isolines error a bit. The stacktrace seems to identify Line as you suggested. 

![image](https://user-images.githubusercontent.com/390250/189543506-87579a37-ba6e-472d-ad29-724c7323e213.png)

Not sure if I will know how to move on. 

On a sidenote I am synchronizing the executeJob method using a Lock, else it doesn't work for me.  Not sure if this could be part of the issue.

**Comment by moovida** [comment]
I debugged the issue into FlutterPaint, where the getClonedImage is called on an image that has already been disposed. I was hoping for a method to check disposal, but cant find any.  I also am not sure if that would be a wise thing to do, since I have no idea why the image is already disposed.

**Comment by mikes222** [comment]
Regarding disposed images: You can give each image a name (e.g. source of the image). This way you can easily find out what kind of image that is you can find out when this image is created/cloned/destroyed. 

Since there are way too many topics in this thread I will close it now and ask to open another issue if needed.

**Comment by moovida** [comment]
A small update after upgrading to the current master branch. The strange pattern when using contourlines are now fixed. Maps look beautiful :-)


![image](https://github.com/mikes222/mapsforge_flutter/assets/390250/b740ab13-8ce6-481e-ba0d-2b9818a60243)
