### ISSUE TITLE
Download Error in apk release version

### ISSUE THREAD

**Issue by Davomat** [mikes222/mapsforge_flutter#72]
When trying out the example app or using the library in debug-mode respectively, things work fine. But when installing the apk's release version, download errors occur.

Here are two example screenshots in the example app.

<img src="https://user-images.githubusercontent.com/53982746/193296286-753a2c84-abee-4f09-9f46-718afdf37783.jpg" width=40% height=40%> &emsp; <img src="https://user-images.githubusercontent.com/53982746/193296366-8899781a-f25b-46be-8955-f966868ca1b5.jpg" width=40% height=40%>

**Comment by mikes222** [comment]
The download functionality in the demo app are only for demonstration purposes and is not part of the mapsforge library. I suggest to check the www for informations about AndroidManifest.xml

    
    <uses-permission android:name="android.permission.INTERNET" />

**Comment by Davomat** [comment]
Thank you for the information. I was concerned there might be some kind of permissions error in the library, but I'm glad to hear it is an external issue.
