### ISSUE TITLE
Simple example showing adding a custom Marker (svg)

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#73]
I've studied the code in /Example, but haven't found a way to simply add a marker to the map. The example shows a popupmenu with which a marker can be added/deleted. To be honest, the code itself, contrary to the original MapsForge, does not look trivial to me.

Also, I cannot get the sample shown at https://pub.dev/packages/mapsforge_flutter#marker to work. No errors are shown, but also no Marker.

What I'm missing and seeking for is to respond to an Event (tap, double tap, longpress, etc.):
- When on Map, add Marker at the screen location touched
- When on Marker, delete or move Marker
- Show custom dialog when Event occurs on Map or Marker to allow user to create Marker with properties, or add properties for the selected Marker.

Any help would be appreciated.

**Comment by mikes222** [comment]
Good usecase. I am confident this is possible without tweaking the system. However I won't have time this week anymore to give you detailed hints. 
In the meantime you could check the ``GestureHandlerDetector``. It sends an event in case of tap. You could catch that event and work with it.

btw. If you have suggestions for a simpler API just create a new issue or even a PullRequest.

**Comment by pamtbaau** [comment]
I've found `viewModel.observeTap.listen()' and that worked for adding a Marker:
```
viewModel.observeTap.listen((event) async {
  var marker = PoiMarker(
    markerCaption: MarkerCaption(text: 'XXX'),
    latLong: LatLong(52.5211, 13.3905),
  );
});
```
If I save the marker in a variable, it can be removed using ` markerDataStore.removeMarker(myMarker);`

Unfortunately, I've only been able to add a Marker using `markerCaption`. Trying to add a Marker with an image fails. No error is thrown, but also no marker is shown.
```
marker = PoiMarker(
  src: 'lib/assets/icons/xx.svg',  // or  'lib/assets/icons/xx.png', or ...
  latLong: LatLong(52.5211, 13.3905),
);
markerDataStore.addMarker(marker);
```

Todo:
- Add Marker while displaying a dialog
- Find tapped Marker and delete it
- Find tapped Marker and open Dialog to add/change properties
