### ISSUE TITLE
Feature request: Adding Alignment option to Markers relative to touchpoint

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#74]
When adding point of interest to a map, centering the PoiMarker is a good default. However depending on the type of marker (e.g. ![marker](https://user-images.githubusercontent.com/5120011/206721058-01d38557-5884-49c3-9704-9f5f6c38101a.png)), bottom_center would be a more suitable alignment.

To prevent users to create svg/png files that have the bottom on the Marker at midpoint of the png/svg file, an alignment option would be handy.

It could be added at either `markerDataStore.addMarker(marker, Alignment.bottom_center)`, or as default value for the `XyzMarker(... alignment: Alignment.bottom_center)`

**Comment by mikes222** [comment]
Do you have an implementation of this feature already? If so please create a PullRequest.

**Comment by pamtbaau** [comment]
No, I've created an svg marker which has it point in the middle of the image.

**Comment by pamtbaau** [comment]
See PR https://github.com/mikes222/mapsforge_flutter/pull/78
