### ISSUE TITLE
How does MapFile.from(filename, ...) read the map from disk

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#75]
I've multiple apps on my Android mobile that use the same Map. The file is approx. 750Mb in size.

When downloading the Map from mapsforge and storing it in folder getApplicationDocumentsDirectory(), all goes well.
- `File.writeAsBytes(downloadedBytes);` saves the map
- `MapFile mapFile = await MapFile.from(filePath, null, null);` reads the file without a problem.

Unfortunately, downloading the map for each app and storing it in each apps private disk area seems a waste of resources.

Therefor I would like to share a single file on the sdcard. For this, I need to use Androids Storage Access Framework to read/write the data. Writing works fine, but when reading the file using `FileInputStream.readBytes()`, I get an OutOfMemory exception. 

I'm trying to narrow size the possible problem area:
- No matter how large I set the internal memory of the emulator, it keeps throwing OOM exceptions.
- A native Android/Kotlin app using `MapFile(inputStream, 0, null)` works fine.
- Just wondering, does `MapFile.from(filePath, null, null);`  read the entire Map into memory, or does it slice and dice to get only the relevant data needed for the visible area and zoomfactor?

Any suggestions?

**Comment by mikes222** [comment]
MapFile reads only the interesting portions of the file into memory when needed. Don't try to load the complete mapfile at once into memory, it will not work except for really tiny mapfiles.

**Comment by mikes222** [comment]
``MapFile`` uses ``ReadBufferFile`` for randomAccess of the file's content. The relevant code is in line 91. It opens the file with 

        File file = File(filename);

So in fact every path which is accessible from the File() command should work for you. 
Just build the path and submit it via ``MapFile.from()``

**Comment by pamtbaau** [comment]
> MapFile reads only the interesting portions of the file into memory when needed. 

Ah, that confirms my suspicion...

So currently it is not possible to use the sdcard which cannot be accessed using `File()`.

From a brief look at the code, it doesn't seem easy to replace all access to the *.map file with SAF. Or can it?

**Comment by mikes222** [comment]
1. Implement your own ``ReadBufferSource`` similar to ``ReadBufferFile`` but with methods needed to access SAF
2. Enhance ''MapFile'' with an additional Constructor to submit your own instance of ``ReadBufferSource``
3. Test it and submit the enhancements via PullRequest to this project

Note: I don't know what is needed to access SAF. If many libs are needed or the implementation is too dangerous just add the ``MapFile`` enhancements to this project.

**Comment by pamtbaau** [comment]
Thanks for the pointers. I'll play with it and I'll get back to you.

> I don't know what is needed to access SAF

Roughly (see [Writing custom platform-specific code](https://docs.flutter.dev/development/platform-integration/platform-channels)):
- Setup channel to communicate with native Activity
- */android/app/src/main/AndroidManifest.xml* needs required permissions added
- */android/app/src/main/kotlin/<correct/package/name/>MainActivity.kt* needs code
  - to handle requests sent through channel. Requests like:
    - asking for read/write permission for folder selected by user (and app needs to save Uri of saved file for later access)
    - save downloaded map
    - read map data
