### ISSUE TITLE
How to draw a route

### ISSUE THREAD

**Issue by mrbulut** [mikes222/mapsforge_flutter#76]
recently I have been working on your package. could you help me about how draw a route from point to point?

**Comment by mikes222** [comment]
I hope you found it out in the meantime. 
Please use the ``PathMarker`` for this. Create a ``Datastore`` as explained in the docu and add a PathMarker and add the desired waypoints inclusive the starting waypoint with ``addLatLong()`` to the pathMarker. If you want to change the route you can call ``clear()`` and add the new route (don't forget to call ``setRepaint()`` to instruct the system to repaint the markers next time)

**Comment by mrbulut** [comment]
I was using PolygonMarker instead of PathMarker. The route paint wasn't quality and there were litter spaces between points. Now the route is more quality than used before and no space between points. Thanks for answering

**Comment by mrbulut** [comment]
By the way, i would like to remove the tap events from the map. How can I remove it?

**Comment by mikes222** [comment]
Do not set up a ``ContextMenuBuilder``. It will be instantiated (if defined) when a ``widget.viewModel.observeTap`` event is triggered.
