### ISSUE TITLE
simplified_example won't work

### ISSUE THREAD

**Issue by lordbavaria13** [mikes222/mapsforge_flutter#80]
Hi,
your simplified_example won't work, because your mapModel throws an execption because it is not initialized.

On the other hand your flutter example do not work, because it is not possible to read the .map File.

**Comment by mikes222** [comment]
Hi, thanks for the hints. I will recheck and correct the examples in the next days. In the meantime try to use the code from github master-branch instead of the official pub.dev upload. The master branch is much newer.

**Comment by mikes222** [comment]
examples cleaned-up and refactored a bit.
