### ISSUE TITLE
Multiple maps support

### ISSUE THREAD

**Issue by zmesinger** [mikes222/mapsforge_flutter#82]
Hello,

I am using maps plugin for displaying map file and it is working as it should, but now I am in need of displaying multiple map files at the same time and I cannot find the information if the plugin supports it and if it does how can it be achieved.
Plugin version I am using is: 
`2.0.2`

Thank you in advance.

**Comment by mikes222** [comment]
For development purposes always github source:

    mapsforge_flutter:
        git: https://github.com/mikes222/mapsforge_flutter

Have a look at ``MapViewPage2`` in the example. I would create 2 pages similar to this page and add them side-by-side as desired in the parent.

In theory it should work. If you experience any troubles please create tickets accordingly.
