### ISSUE TITLE
PoiMarker.captionOffsetY not working

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#85]
When creating a `PoiMarker` with a `CaptionLabel`, setting `captionOffsetX` is working correctly, but nothing happens when setting `captionOffsetY`

NB. I'm using commit "ssl domain changed, sorry need to do this for another project" since later commits do not show markers.

**Comment by mikes222** [comment]
As mentioned in another issue, ``dy`` should be used instead. If there is a usecase for dx, just explain it and I will add it too (or you could add a PullRequest with the proposed changes.

**Comment by pamtbaau** [comment]
The new `MarkerCaption.position` property is fulfilling my current needs.
