### ISSUE TITLE
Feature: Allow multiple MarkerCaptions per Marker

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#87]
I would like to display multiple captions for a single Marker. For example different captions for Id, Name, Count. The captions could then be placed at different positions alongside the Marker, eg. Id top-left, Name top-right and Count below Name.

**Comment by mikes222** [comment]
Finally this is implemented. Do it like so:

    PoiMarker circleMarker = PoiMarker(
      latLong: latLong,
      displayModel: displayModel,
      src: "jar:symbols/tourist/view_point.svg",
    )
      ..addCaption(
          Caption(caption: "Markercaption", displayModel: displayModel))
      ..addCaption(Caption(
          caption: "Markercaption",
          displayModel: displayModel,
          fontSize: 16,
          position: Position.ABOVE))
      ..addCaption(Caption(
          caption: "Markercaption",
          displayModel: displayModel,
          fontSize: 8,
          position: Position.RIGHT));
