### ISSUE TITLE
Feature: Add text-align (left, right, center) to MarkerCaption

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#88]
It would be nice to add a text-align (Left, Right, Center) to the MarkerCaption. 
- Using right-align would be very convenient to position a Caption on the left edge of the Marker without the need to calculate the width of the Label for proper positioning.
- Center would be very convenient when the center of the Caption should be at the bottom-center of the Marker

**Comment by mikes222** [comment]
Check this testcase. Is this what you want?

![poimarker_bottomcenter_text_left](https://user-images.githubusercontent.com/2129663/234958752-9722942d-63de-407a-a449-10da37132f00.png)

**Comment by pamtbaau** [comment]
Seeing your commit a few minutes ago and have tested it. I think it solves my issue, but in a different way then I expected...

Before the Position option, I was trying the move the MarkerCaption using the x/y offse

**Comment by mikes222** [comment]
captionOffsetX/captionOffsetY makes no sense anymore. Use dy instead. If needed I can later also add dx.

**Comment by pamtbaau** [comment]
Uhh... I don't see a dY anywhere in MarkerCaption, only captionOffsetX/captionOffsetY... Am I missing something?

**Comment by mikes222** [comment]
made it available now.

**Comment by pamtbaau** [comment]
Yes, inside class `CaptionMarker`, but not in class `MarkerCaption`. :-)

A PoiMarker has property `MarkerCaption? markerCaption` and not `CaptionMarker`
