### ISSUE TITLE
Alignment PoiMarker no longer functioning

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#89]
It seems that alignment of PoiMarker has been erased since https://github.com/mikes222/mapsforge_flutter/commit/722350b4c47d020d45af1256e29233b288d9ca02

**Comment by mikes222** [comment]
Fixed. Replaced parameter ``alignment`` with already existing parameter ``position``. Added unittest.

**Comment by pamtbaau** [comment]
Thanks, seems to be working just fine!
