### ISSUE TITLE
Has TapEvent.widgetPixelMappoint been removed by design?

### ISSUE THREAD

**Issue by pamtbaau** [mikes222/mapsforge_flutter#90]
When a user taps the map, I show a `popupMenu` for the Marker closest to the tapped location. 

Inside `viewModel.observeTap.listen((event) {...})`, I used to use the `event.widgetPixelMappoint.x` and `event.widgetPixelMappoint.y` properties of the event to calculate the position for the popupMenu.

Since the `event.widgetPixelMappoint.x`/`event.widgetPixelMappoint.y` properties have been removed I don't see a way to calculate the proper offset for the `popupMenu` anymore.

Any suggestions?

**Comment by mikes222** [comment]
This is not working for rotating maps anymore therefore I removed it. See ``DefaultContextMenu`` for a working alternative.

**Comment by pamtbaau** [comment]
Thanks, will have a look at the calculation used by `DefaultContextMenu`.
