### ISSUE TITLE
Change map theme to dark

### ISSUE THREAD

**Issue by mserkanguzel** [mikes222/mapsforge_flutter#94]
Hi, first of all thank you for developing this package.
We use offline map, so;

```
 static const String MAP_THEME_PATH_URL = "assets/render_themes/defaultrender.xml";
 static const String MAP_DARK_THEME_PATH_URL = "assets/render_themes/darkrender.xml";
 
```
 I was using changeKey method in MapviewWidget and tried refresh but didn't works.

How can I change theme with dynamically? For example click change button or etc.

**Comment by mikes222** [comment]
First make sure that toggling themes are working for your app regardless of the mapsforge-plugin. That means you need to have the themes configured in your ```MaterialApp`` widget and also have your ``ThemeProvider`` with ``ChangeNotifier`` configured correctly. This is required so that the mapsforge widget gets rebuilt if the theme changes. Find out more at the usual flutter introductions.

Then make sure that the jobRenderer you create uses the correct Rendertheme. This is an excerpt from my code for the dark theme:

    RenderTheme renderTheme = await RenderThemeBuilder.create(
          displayModel, "assets/darkrender.xml");
      _darkDataStoreRenderer = MapDataStoreRenderer(
          _multiMapDataStore!, renderTheme, _symbolCache, false);
