### ISSUE TITLE
Real time location tracking only updates when map is moved

### ISSUE THREAD

**Issue by vasilevzhivko** [mikes222/mapsforge_flutter#97]
I am trying to implement a user location marker, with the following code:

```
import 'dart:async';

import 'package:hikerbg/app/services/gps/gps_service.dart';
import 'package:hikerbg/core/models/pos.dart';
import 'package:mapsforge_flutter/core.dart';
import 'package:mapsforge_flutter/marker.dart';

class UserPositionMarker extends MarkerByItemDataStore {
  final SymbolCache symbolCache;
  final DisplayModel displayModel;

  Pos? position;

  late StreamSubscription sub;

  UserPositionMarker(
      {required this.symbolCache, required this.displayModel, this.position}) {
    sub = GpsService.observe.listen((pos) {
      position = Pos(pos.latitude, pos.longitude);
      setRepaint();
    });
  }

  @override
  Future<void> retrieveMarkersFor(BoundingBox boundary, int zoomLevel) async {
    if (position != null) {
      replaceMarker("USER_POSITION", await _createMarker());
      setRepaint();
    }
  }

  Future<BasicMarker> _createMarker() async {
    PoiMarker marker = PoiMarker(
      item: "USER_POSITION",
      displayModel: displayModel,
      latLong: LatLong(position!.lat, position!.lon),
      src: "assets/images/walk-2.png",
      width: 45,
      height: 45,
    );
    await marker.initResources(symbolCache);

    return marker;
  }

  @override
  void dispose() {
    super.dispose();
    sub.cancel();
  }
}

```
so far the marker is updated, but I noticed two issues.

1. Even tho I am using replaceMarker, the old location marker is still displayed on the map.
2. The new location marker is only updated when the map is slightly moved.

I guess the second issue is because the map stream only tracks map position and then it rebuilds the map.

```
 @override
  Widget build(BuildContext context) {
    return StreamBuilder<MapViewPosition>(
      stream: widget.viewModel.observePosition,
      builder: (BuildContext context, AsyncSnapshot<MapViewPosition> snapshot) {
        //print("position ${snapshot.connectionState} with ${snapshot.data}");
        if (snapshot.connectionState == ConnectionState.waiting)
          return _buildNoPositionView();
        if (snapshot.hasData) {
          if (snapshot.data!.hasPosition()) {
            //_log.info("I have a new position ${snapshot.data.toString()}");
            return _buildMapView(snapshot.data!);
          }
          //return _buildNoPositionView();
        }
        if (widget.viewModel.mapViewPosition != null &&
            widget.viewModel.mapViewPosition!.hasPosition()) {
          //_log.info(
          //    "I have an old position ${widget.viewModel.mapViewPosition!.toString()}");
          return _buildMapView(widget.viewModel.mapViewPosition!);
        }
        return _buildNoPositionView();
      },
    );
  }
```

any ideas how to bypass this?

p.s. code for GpsService in case of anyone is interested:

```
import 'dart:async';

import 'package:geolocator/geolocator.dart';
import 'package:rxdart/rxdart.dart';
class GpsService {
  static final Subject<Position> _inject = BehaviorSubject<Position>();

  static Stream<Position> get observe => _inject.stream;

  StreamSubscription<Position>? gpsStream;

  Position? get lastPos {
    return _lastPos;
  }

  Position? _lastPos;

  /// Determine the current position of the device.
  ///
  /// When the location services are not enabled or permissions
  /// are denied the `Future` will return an error.
  Future<Position> determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    return await Geolocator.getCurrentPosition()
        .then((pos) => _lastPos = pos)
        .then((_) => _inject.add(_lastPos!))
        .then((_) => _lastPos!);
  }

  void startPositioning() {
    if (gpsStream != null) {
      return;
    }
    gpsStream = Geolocator.getPositionStream().listen((event) {
      _lastPos = event;
      _inject.add(event);
    });
  }

  void stopPositioning() {
    if (gpsStream == null) {
      return;
    }
    gpsStream!.cancel();
    gpsStream = null;
  }
}
```

**Comment by mikes222** [comment]
``setRepaint()`` only triggers a repaint for the marker, but does not trigger a general repaint of the underlying widget. The easiest way to do this is to slightly change the position of the map. If this is not an option I need to implement a method in ``ViewModel`` to inject the current position into ``_injectPosition``.

**Comment by vasilevzhivko** [comment]
> `setRepaint()` only triggers a repaint for the marker, but does not trigger a general repaint of the underlying widget. The easiest way to do this is to slightly change the position of the map. If this is not an option I need to implement a method in `ViewModel` to inject the current position into `_injectPosition`.

The problem with that is if you want to browse around you, the map always return to your position (when using listen from the geolocator the location is updated pretty much every second).
I am currently testing an implementation with another stream and additional parameter for the map (display realtime location) and repaint only the user marker. Something like that:

```
 @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        StreamBuilder<MapViewPosition>(
          stream: widget.viewModel.observePosition,
          builder: (BuildContext context, AsyncSnapshot<MapViewPosition> snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return _buildNoPositionView();
            }
            if (snapshot.hasData && snapshot.data!.hasPosition()) {
              return _buildMapView(snapshot.data!);
            }
            if (widget.viewModel.mapViewPosition != null &&
                widget.viewModel.mapViewPosition!.hasPosition()) {
              return _buildMapView(widget.viewModel.mapViewPosition!);
            }
            return _buildNoPositionView();
          },
        ),
        StreamBuilder<UserLocation>(
          stream: widget.viewModel.observeUserLocationMarker,
          builder: (context, userLocationSnapshot) {
            if (userLocationSnapshot.hasData) {
              UserLocation userLocation = userLocationSnapshot.data!;
              return CustomPaint(
                foregroundPainter: MarkerPainter(
                  mapViewPosition: widget.viewModel.mapViewPosition!,
                  dataStore: UserPositionMarker(
                    symbolCache: widget.mapModel.symbolCache,
                    displayModel: widget.mapModel.displayModel,
                    viewModel: widget.viewModel,
                    position: Pos(userLocation.latitude, userLocation.longitude),
                  ),
                  viewModel: widget.viewModel,
                ),
                child: const SizedBox.expand(),
              );
            }
            return const SizedBox();
          },
        ),
      ],
    );
  }
```

If you are open for the idea, I can also try to implement the real time location pin directly in the library but I have to reference geolocator.

**Comment by vasilevzhivko** [comment]
hey @mikes222 I am trying to implement some live user location, but I am not able to figure out what rebuilds the map.
I've opened this draft PR ([https://github.com/mikes222/mapsforge_flutter/pull/99]) with what I have done so far. Can you please check it and leave your comments on it.

**Comment by pamtbaau** [comment]
I might miss some important points in your use case, but this is what I understand:
- You want to add a marker showing the current gps location to the map
- You don't want the the map to be centered around the gps location.

What I do in my app:
- I use variable `isCentered`, which can be switched on/off. Mostly I want the map to follow my position, but sometimes i want to look around.
- The marker showing the current GPS location has its own MarkerDataStore.
I do not use `replaceMarker` but just wipe the MarkerDataStore and add a new marker.
- The following code will use `isCentered`
  ```
  // The following method is called whenever the parent widget, which holds the gps stream, 
  // notifies the map using `controller.gpsLocation`
  void _setGpsLocation() {
    _addPositionMarker();

    if (widget.isCentered) {
      _viewModel.setMapViewPosition(
         _controller.gpsLocation.latitude,
         _controller.gpsLocation.longitude,
       );
    }
  }

  Future<void> _addPositionMarker() async {
    _positionDataStore.clearMarkers();

    if (_controller.gpsLocation == null) return;

    final positionMarker = PoiMarker(
      displayModel: DisplayModel(),
      src: 'lib/assets/icons/position.svg',
      height: 32,
      width: 32,
      latLong: _controller.gpsLocation!,
      position: Position.CENTER,
    );

    await positionMarker.initResources(_symbolCache);
    _positionDataStore.addMarker(positionMarker);
    _positionDataStore.setRepaint();
  }
  ```

**Comment by vasilevzhivko** [comment]
> I might miss some important points in your use case, but this is what I understand:
> 
> * You want to add a marker showing the current gps location to the map
> * You don't want the the map to be centered around the gps location.
> 
> What I do in my app:
> 
> * I use variable `isCentered`, which can be switched on/off. Mostly I want the map to follow my position, but sometimes i want to look around.
> * The marker showing the current GPS location has its own MarkerDataStore.
>   I do not use `replaceMarker` but just wipe the MarkerDataStore and add a new marker.
> * The following code will use `isCentered`
>   ```
>   // The following method is called whenever the parent widget, which holds the gps stream, 
>   // notifies the map using `controller.gpsLocation`
>   void _setGpsLocation() {
>     _addPositionMarker();
>   
>     if (widget.isCentered) {
>       _viewModel.setMapViewPosition(
>          _controller.gpsLocation.latitude,
>          _controller.gpsLocation.longitude,
>        );
>     }
>   }
>   
>   Future<void> _addPositionMarker() async {
>     _positionDataStore.clearMarkers();
>   
>     if (_controller.gpsLocation == null) return;
>   
>     final positionMarker = PoiMarker(
>       displayModel: DisplayModel(),
>       src: 'lib/assets/icons/position.svg',
>       height: 32,
>       width: 32,
>       latLong: _controller.gpsLocation!,
>       position: Position.CENTER,
>     );
>   
>     await positionMarker.initResources(_symbolCache);
>     _positionDataStore.addMarker(positionMarker);
>     _positionDataStore.setRepaint();
>   }
>   ```

hey @pamtbaau thanks for the tip. However it seems like I am missing something. Can you share more details on your _controller?
I am trying to implement it using Provider, and so far I have to following setup:

```
class MapViewModel with ChangeNotifier {
  late MapDataStore map;
  late JobRenderer jobRenderer;
  late SymbolCache symbolCache = FileSymbolCache();
  late FileTileBitmapCache bitmapCache;
  late DisplayModel displayModel =
      DisplayModel(fontScaleFactor: 0.5, maxZoomLevel: 19);
  late ViewModel viewModel;
  late MapModel mapModel;
  bool initialLocationSet = false;
  MarkerByItemDataStore currentLocationMarkerStore = MarkerByItemDataStore();
  MarkerByItemDataStore hutsMarkerstore = MarkerByItemDataStore();

  StreamSubscription<geo.Position>? _gpsSubscription;

  Future<void> initializeMap() async {
    try {
      ByteData content =
          await rootBundle.load('assets/map/mapstyles/bgmountains.map');
      map = await MapFile.using(content.buffer.asUint8List(), null, null);

      // Initialize render theme and renderer
      final renderTheme = await RenderThemeBuilder.create(
        displayModel,
        'assets/map/mapstyles/Elevate.xml',
      );

      jobRenderer = MapDataStoreRenderer(map, renderTheme, symbolCache, true);

      bitmapCache =
          await FileTileBitmapCache.create(jobRenderer.getRenderKey());
      bitmapCache.purgeAll();

      viewModel = ViewModel(
        displayModel: displayModel,
        contextMenuBuilder: null, // Remove default ContextMenuBuilder
      );

      viewModel.setZoomLevel(18);

      mapModel = MapModel(
        displayModel: displayModel,
        renderer: jobRenderer,
        tileBitmapCache: bitmapCache,
        symbolCache: symbolCache,
      );

      mapModel.markerDataStores.add(currentLocationMarkerStore);
      mapModel.markerDataStores.add(hutsMarkerstore);

      // Start listening to GPS updates
      _startGpsListening();

      notifyListeners(); // Notify listeners that everything is initialized
    } catch (e) {
      print('Failed to initialize map: $e');
      throw Exception('Failed to initialize MapViewModel');
    }
  }

  void _startGpsListening() {
    _gpsSubscription = GpsService.observe.listen((position) {
      if (!initialLocationSet) {
        viewModel.setMapViewPosition(position.latitude, position.longitude);
        initialLocationSet = true;
      }
      _updatePositionMarker(Pos(position.latitude, position.longitude));
    });
  }

  Future<void> _updatePositionMarker(Pos position) async {
    currentLocationMarkerStore.clearMarkers();

    final positionMarker = PoiMarker(
      displayModel: displayModel,
      src: 'assets/images/walk-2.png',
      height: 32,
      width: 32,
      latLong: LatLong(position.latitude, position.longitude),
      position: Position.CENTER,
    );

    await positionMarker.initResources(symbolCache);
    currentLocationMarkerStore.addMarker(positionMarker);
    currentLocationMarkerStore.setRepaint();

    notifyListeners(); // Notify listeners that the marker has been updated
  }

  @override
  void dispose() {
    _gpsSubscription?.cancel();
    super.dispose();
  }
}

```

then my main build method:
```
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FutureBuilder(
        future:
            Provider.of<MapViewModel>(context, listen: false).initializeMap(),
        builder: (context, snapshot) {
          if (snapshot.connectionState != ConnectionState.done) {
            return const LoadingView(); // Show loading until the initialization is done
          }
          if (snapshot.hasError) {
            return Center(
                child: Text('Error initializing map: ${snapshot.error}'));
          }
          return const MainScaffold(body: MapPage());
        },
      ),
    );
  }
```

and in the widget where I am consuming the Map I have the map wrapped in a consumer:
```
    return Consumer<MapViewModel>(
      builder: (context, mapViewModel, child) {
        return Stack(
          children: [
            FlutterMapView(
              mapModel: mapViewModel.mapModel,
              viewModel: mapViewModel.viewModel,
            ),
```

but the widget is only drawn once and not updated once the location changes

**Comment by mikes222** [comment]
It may be much simpler: 

- Whenever the viewModel is created send it to your gps-provider and start listening
- Whenever the view is disposed() remove viewModel from your gps-provider and stop listening
- whenever gps position changes AND you want to update the view's position call ``viewModel.setMapViewPosition()``

That's it. 

For example take the ``simpified-example`` project. 
- Add an import rxdart/rxdart
- Add the following code after ``viewModel.setZoomLevel()`` around line 95

    Future.delayed(const Duration(seconds: 10), () {
      Stream.fromIterable(List.generate(1000, (idx) => idx))
          .interval(const Duration(milliseconds: 50))
          .forEach((value) {
        viewModel.setMapViewPosition(
            50.84 + value / 100000, 12.93 + value / 100000);
      });
    });

This simulates gps-updates after 10 seconds without changing or duplicating any code of this library.

**Comment by vasilevzhivko** [comment]
> It may be much simpler:
> 
> * Whenever the viewModel is created send it to your gps-provider and start listening
> * Whenever the view is disposed() remove viewModel from your gps-provider and stop listening
> * whenever gps position changes AND you want to update the view's position call `viewModel.setMapViewPosition()`
> 
> That's it.
> 
> For example take the `simpified-example` project.
> 
> * Add an import rxdart/rxdart
> * Add the following code after `viewModel.setZoomLevel()` around line 95
>   Future.delayed(const Duration(seconds: 10), () {
>   Stream.fromIterable(List.generate(1000, (idx) => idx))
>   .interval(const Duration(milliseconds: 50))
>   .forEach((value) {
>   viewModel.setMapViewPosition(
>   50.84 + value / 100000, 12.93 + value / 100000);
>   });
>   });
> 
> This simulates gps-updates after 10 seconds without changing or duplicating any code of this library.

That works, the problem is I dont want to update the position.
I am building an app for offline hiking navigation and one of my crucial points is to be able to browse around you and not move the map always to the current location.

**Comment by pamtbaau** [comment]
@vasilevzhivko, Do you have a repo I can clone?

**Comment by vasilevzhivko** [comment]
> @vasilevzhivko, Do you have a repo I can clone?

the problem was I forgot to call startPositioning from the GpsService.... quite embarrassing :) anyway your solution works 100%. Thanks!
